// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUEO1O67b4wvckWIC35cbeLnZXc-QUCXI',
    appId: '1:54544069787:web:0912ebd836b4394190c23e',
    messagingSenderId: '54544069787',
    projectId: 'todo-list-providerjb',
    authDomain: 'todo-list-providerjb.firebaseapp.com',
    storageBucket: 'todo-list-providerjb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjbDLu46-n_To94d310-KnmtRSo2CPYPg',
    appId: '1:54544069787:android:05053587558a4af390c23e',
    messagingSenderId: '54544069787',
    projectId: 'todo-list-providerjb',
    storageBucket: 'todo-list-providerjb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFtAoEPFsPPJPJEygU7Vp45uhNpdzn4AU',
    appId: '1:54544069787:ios:cb0fdbf0f992756390c23e',
    messagingSenderId: '54544069787',
    projectId: 'todo-list-providerjb',
    storageBucket: 'todo-list-providerjb.appspot.com',
    iosClientId: '54544069787-1m54nalm4r0tv1mr3l4nea98fmc2kesm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFtAoEPFsPPJPJEygU7Vp45uhNpdzn4AU',
    appId: '1:54544069787:ios:cb0fdbf0f992756390c23e',
    messagingSenderId: '54544069787',
    projectId: 'todo-list-providerjb',
    storageBucket: 'todo-list-providerjb.appspot.com',
    iosClientId: '54544069787-1m54nalm4r0tv1mr3l4nea98fmc2kesm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider',
  );
}
